Update examples to latest syntax

diff --git a/examples/02-options.yaml b/examples/02-options.yaml
--- a/examples/02-options.yaml
+++ b/examples/02-options.yaml
@@ -1,24 +1,22 @@
 
-targets:
-
 # tame -f examples/02-options.yaml SoundOfSilence
-  SoundOfSilence:
-    run:
-    - sh: echo "hello darkness"
-      opts: silent # stdout and stderr is not printed
-    - sh: |
-        echo "i fail but.."
-        exit 66
-      opts: allowed-fail # allow non-zero return codes and continue execution
-    - sh: echo "target execution still finished"
+SoundOfSilence:
+  run:
+  - sh: echo "hello darkness"
+    opts: silent # stdout and stderr is not printed
+  - sh: |
+      echo "i fail but.."
+      exit 66
+    opts: allowed-fail # allow non-zero return codes and continue execution
+  - sh: echo "target execution still finished"
 
 # tame -f examples/02-options.yaml MultipleOpts
-  MultipleOpts:
-    run:
-      - sh: |
-          echo "verbose cmd"
-          exit 42
-        opts: [silent, allowed-fail]
+MultipleOpts:
+  run:
+    - sh: |
+        echo "verbose cmd"
+        exit 42
+      opts: [silent, allowed-fail]
 
 
 
