Fix async examples

diff --git a/examples/13-async.yaml b/examples/13-async.yaml
--- a/examples/13-async.yaml
+++ b/examples/13-async.yaml
@@ -1,43 +1,41 @@
 settings:
   shell: /bin/bash
+  shieldEnv: true
+
 targets:
-  foo:
+ # tame -f examples/14-async-usage.yaml parallelJobsSuccess
+  parallelJobsSuccess:
+    # the second step will run without waiting for the first to finish
     run:
-      - sh: |
-          for i in {1..4}; do
-            sleep 1
-            echo Waiting... $i
-          done
-        opts: async
-      - sh: sleep 1 && echo "this runs async too"
-        opts: async
-      - sh: echo this still runs && sleep 1
-      - sh: echo this finishes && sleep 5
-      - sh: exit 5
+    - sh: for i in {1..4}; do echo "first job...$i"; sleep 1; done
+      opts: async
+    - sh: for i in {1..4}; do echo "second job...$i"; sleep 1; done
+      opts: async
+    # the last async opt is not actually needed, it's there to demonstrate that at the end of the target
+    # we wait for all async steps to finish, before continuing
 
-  for:
+  parallelJobsFailure:
+    # the second step will run without waiting for the first to finish
+    # when the first step fails, the second step will terminate too
     run:
-      - sh: |
-          for i in {1..6}; do
-            echo Waiting in background... $i
-            sleep 1
-          done
-        opts: async
-      - for: { $: $i, in: ["x", "y", "z"] }
-        sh: sleep 1 && echo "this runs async too $i"
-        opts: async
-      # - sh: sleep 1 && echo "exiting 42" && exit 42
-      #   opts: async
-      - sh: echo 1 sync && sleep 1
-      - sh: echo 2 sync && sleep 1
-      - sh: echo 3 sync && sleep 1
-      - sh: echo This runs in sync
-      - sh: echo good bye with 2 && exit 2
-      - sh: echo This SHOULD NOT RUN since we exited with 2
-      - sh: echo "THIS SHOULDNT RUN EITHER"
+    - sh: echo "i will fail in 2 sec"; sleep 2; exit 42
+      opts: async
+    - sh: for i in {1..4}; do echo "second job...$i"; sleep 1; done
+      opts: async
+    # the execution will finish early since the first job fails
 
-  bus:
+  parallelJobsAllowedFailure:
+    # the second step will finish, even though the first one failed,
+    # this is due to the allowed-fail option
     run:
-      - sh: exit 45 && echo "hello again"
-        opts: async
-      - sh: echo "loveya with a 1"
+    - sh: echo "i will fail in 2 sec"; sleep 2; exit 42
+      opts: [async, allowed-fail]
+    - sh: for i in {1..4}; do echo "second job...$i"; sleep 1; done
+      opts: async
+
+  parallelForLoop:
+    run:
+    # Each step will execute in parallel
+    - for: {$: $name, in: ["Alice","Bob","Cathy"]}
+      sh: echo "Hi ${name}!"
+      opts: async
